<?xml version="1.0" encoding="utf-8"?><Database Name="MISDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-QG4F7NB;Initial Catalog=MISDB;Persist Security Info=True;User ID=sa" SettingsObjectName="yangpeng1._0.Properties.Settings" SettingsPropertyName="MISDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Department" Member="Department">
    <Type Name="Department">
      <Column Name="Departmentid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>